language: java

jdk:
  - openjdk9

before_install:
  - echo "this is before install section"
  

install:
  - echo "this is installation part"

env:
 - Test1="test"
 # target environment to deploy (docker, ec2, k8s)
 - DEPLOYMENT_TARGET=docker

before_script:
  - echo "this is before script section"

script:
  - echo "this is the script section"
  

after_success:
  - echo "yaaaaaay succeeded .. everything is working fine now "

after_failure:
  - echo "Sorry the job is failed .. please check the reason"

after_script:
  - echo "after script section"

branches:
  only:
    - develop
    - master

jenkins:
  platform: docker
#  # lifecycles_standard_stable.json
#  os: standard
#  stability: stable
  sudo: sudo
  pipeline_jenkinsfile: SaaS
  
